### ISSUE TITLE
Movie actors and actresses

### ISSUE THREAD

**Issue by jperasmus** [randfun/movies-dataset#1]
Hi there, thanks for making this dataset.

I was wondering if there is a way to see the actors and actresses for a specific movie?

**Comment by Angelmmiguel** [comment]
Hello @jperasmus,

I got this information from two [IMDB](http://www.imdb.com/list/ls074674014/) [lists](http://www.imdb.com/list/ls058011111/). In the CSV export, the information of the actors and actresses is missing:

```
1,tt0068646,2015-07-21,2015-07-21,,The Godfather,https://www.imdb.com/title/tt0068646/,movie,9.2,175,1972,"Crime, Drama",1461036,1972-03-14,Francis Ford Coppola
2,tt0047478,2015-07-21,2015-07-21,,Shichinin no samurai,https://www.imdb.com/title/tt0047478/,movie,8.6,207,1954,"Adventure, Drama",288295,1954-04-26,Akira Kurosawa
3,tt0071562,2015-07-21,2015-07-21,,The Godfather: Part II,https://www.imdb.com/title/tt0071562/,movie,9.0,202,1974,"Crime, Drama",1016222,1974-12-12,Francis Ford Coppola
```

So, it seems it's not going to be easy to extract this information from IMDB directly. However, I found this interesting dataset: https://data.world/popculture/imdb-5000-movie-dataset. It contains 5000 movies with information about the main 3 actors and directors. This could be a better foundation for this dataset, so it's worth to start using it.

However, I'm afraid I won't be able to work on this soon. Feel free to submit a PR if this is urgent for you :)

**Comment by jperasmus** [comment]
Hi @Angelmmiguel thanks for the response. This was for a play project I was working on, so not very urgent on my side. Was just wondering if I perhaps missed something.

Thanks for the link to the other dataset, I might take a look at it if I need something like this again.
